/*
 * Cloudinary Provisioning API
 * Accounts with provisioning API access can create and manage their **product environments**, **users** and **user groups** using the RESTful Provisioning API.   Provisioning API access is available [upon request](https://cloudinary.com/contact?plan=enterprise) for accounts on an [Enterprise plan](https://cloudinary.com/pricing#pricing-enterprise). 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@cloudinary.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudinary.provisioning.api;

import com.cloudinary.provisioning.ApiException;
import com.cloudinary.provisioning.model.AccessKeyRequest;
import com.cloudinary.provisioning.model.AccessKeyResponse;
import com.cloudinary.provisioning.model.AccessKeyUpdateRequest;
import com.cloudinary.provisioning.model.AccessKeysResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccessKeysApi
 */
@Disabled
public class AccessKeysApiTest {

    private final AccessKeysApi api = new AccessKeysApi();

    /**
     * Generate an access key
     *
     * Generate a new access key.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateAccessKeyTest() throws ApiException {
        String subAccountId = null;
        AccessKeyRequest accessKeyRequest = null;
        AccessKeyResponse response = api.generateAccessKey(subAccountId, accessKeyRequest);
        // TODO: test validations
    }

    /**
     * Get access keys
     *
     * Retrieve an array of all access keys for a product environment.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAccessKeysTest() throws ApiException {
        String subAccountId = null;
        Integer pageSize = null;
        Integer page = null;
        String sortBy = null;
        String sortOrder = null;
        AccessKeysResponse response = api.getAccessKeys(subAccountId, pageSize, page, sortBy, sortOrder);
        // TODO: test validations
    }

    /**
     * Update an access key
     *
     * Update the name and/or status of an existing access key.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateAccessKeyTest() throws ApiException {
        String subAccountId = null;
        String key = null;
        AccessKeyUpdateRequest accessKeyUpdateRequest = null;
        AccessKeyResponse response = api.updateAccessKey(subAccountId, key, accessKeyUpdateRequest);
        // TODO: test validations
    }

}
