/*
 * Cloudinary Provisioning API
 * Accounts with provisioning API access can create and manage their **product environments**, **users** and **user groups** using the RESTful Provisioning API.   Provisioning API access is available [upon request](https://cloudinary.com/contact?plan=enterprise) for accounts on an [Enterprise plan](https://cloudinary.com/pricing#pricing-enterprise). 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@cloudinary.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudinary.provisioning.api;

import com.cloudinary.provisioning.ApiException;
import com.cloudinary.provisioning.model.MessageResponse;
import com.cloudinary.provisioning.model.UserRequest;
import com.cloudinary.provisioning.model.UserResponse;
import com.cloudinary.provisioning.model.UsersResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
@Disabled
public class UsersApiTest {

    private final UsersApi api = new UsersApi();

    /**
     * Create user
     *
     * Create a new user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createUserTest() throws ApiException {
        UserRequest userRequest = null;
        UserResponse response = api.createUser(userRequest);
        // TODO: test validations
    }

    /**
     * Delete user
     *
     * Delete a specific user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteUserTest() throws ApiException {
        String userId = null;
        MessageResponse response = api.deleteUser(userId);
        // TODO: test validations
    }

    /**
     * Get user
     *
     * Retrieve a specific user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUserTest() throws ApiException {
        String userId = null;
        UserResponse response = api.getUser(userId);
        // TODO: test validations
    }

    /**
     * Get users
     *
     * Retrieve an array of users.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUsersTest() throws ApiException {
        Boolean pending = null;
        List<String> ids = null;
        String prefix = null;
        String subAccountId = null;
        UsersResponse response = api.getUsers(pending, ids, prefix, subAccountId);
        // TODO: test validations
    }

    /**
     * Update user
     *
     * Update the details of a user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateUserTest() throws ApiException {
        String userId = null;
        UserRequest userRequest = null;
        UserResponse response = api.updateUser(userId, userRequest);
        // TODO: test validations
    }

}
