/*
 * Cloudinary Account Provisioning API
 * Accounts with provisioning API access can create and manage their **product environments**, **users** and **user groups** using the RESTful Provisioning API.   Provisioning API access is available [upon request](https://cloudinary.com/contact?plan=enterprise) for accounts on an [Enterprise plan](https://cloudinary.com/pricing#pricing-enterprise). 
 *
 * The version of the OpenAPI document: 0.0.2
 * Contact: support@cloudinary.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudinary.provisioning.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProductEnvironmentRequest
 */
public class ProductEnvironmentRequestTest {
    private final ProductEnvironmentRequest model = new ProductEnvironmentRequest();

    /**
     * Model tests for ProductEnvironmentRequest
     */
    @Test
    public void testProductEnvironmentRequest() {
        // TODO: test ProductEnvironmentRequest
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'cloudName'
     */
    @Test
    public void cloudNameTest() {
        // TODO: test cloudName
    }

    /**
     * Test the property 'baseSubAccountId'
     */
    @Test
    public void baseSubAccountIdTest() {
        // TODO: test baseSubAccountId
    }

    /**
     * Test the property 'customAttributes'
     */
    @Test
    public void customAttributesTest() {
        // TODO: test customAttributes
    }

}
