/*
 * Cloudinary Account Provisioning API
 * Accounts with provisioning API access can create and manage their **product environments**, **users** and **user groups** using the RESTful Provisioning API.   Provisioning API access is available [upon request](https://cloudinary.com/contact?plan=enterprise) for accounts on an [Enterprise plan](https://cloudinary.com/pricing#pricing-enterprise).  The API uses **Basic Authentication** over HTTPS. Your **Provisioning Key** and **Provisioning Secret** are used for the authentication. These credentials (as well as your ACCOUNT_ID) are located in the [Cloudinary Console](https://console.cloudinary.com/pm) under **Settings > Account > Provisioning API Access**, or they can be obtained from the provisioning environment variable available on your Cloudinary Console [Dashboard](https://console.cloudinary.com/pm/developer-dashboard).  The Provisioning API has dedicated SDKs for the following languages:  * [JavaScript](https://github.com/cloudinary/account-provisioning-js) * [PHP](https://github.com/cloudinary/account-provisioning-php) * [Java](https://github.com/cloudinary/account-provisioning-java)  Useful links: * [Provisioning API reference (Classic)](https://cloudinary.com/documentation/provisioning_api_1) 
 *
 * The version of the OpenAPI document: 0.1.2
 * Contact: support@cloudinary.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudinary.account.provisioning.api;

import com.cloudinary.account.provisioning.ApiException;
import com.cloudinary.account.provisioning.model.AccessKey;
import com.cloudinary.account.provisioning.model.AccessKeyRequest;
import com.cloudinary.account.provisioning.model.AccessKeyUpdateRequest;
import com.cloudinary.account.provisioning.model.AccessKeysResponse;
import com.cloudinary.account.provisioning.model.ErrorResponse;
import com.cloudinary.account.provisioning.model.SuccessResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccessKeysApi
 */
@Disabled
public class AccessKeysApiTest {

    private final AccessKeysApi api = new AccessKeysApi();

    /**
     * Delete access key
     *
     * Delete a specific access key.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteAccessKeyTest() throws ApiException {
        String subAccountId = null;
        String key = null;
        SuccessResponse response = api.deleteAccessKey(subAccountId, key);
        // TODO: test validations
    }

    /**
     * Delete access key by name
     *
     * Delete a specific access key by name.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteAccessKeyByNameTest() throws ApiException {
        String subAccountId = null;
        String name = null;
        SuccessResponse response = api.deleteAccessKeyByName(subAccountId, name);
        // TODO: test validations
    }

    /**
     * Generate an access key
     *
     * Generate a new access key.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateAccessKeyTest() throws ApiException {
        String subAccountId = null;
        AccessKeyRequest accessKeyRequest = null;
        AccessKey response = api.generateAccessKey(subAccountId, accessKeyRequest);
        // TODO: test validations
    }

    /**
     * Get access keys
     *
     * Retrieve an array of all access keys for a product environment.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAccessKeysTest() throws ApiException {
        String subAccountId = null;
        Integer pageSize = null;
        Integer page = null;
        String sortBy = null;
        String sortOrder = null;
        AccessKeysResponse response = api.getAccessKeys(subAccountId, pageSize, page, sortBy, sortOrder);
        // TODO: test validations
    }

    /**
     * Update an access key
     *
     * Update the name and/or status of an existing access key.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateAccessKeyTest() throws ApiException {
        String subAccountId = null;
        String key = null;
        AccessKeyUpdateRequest accessKeyUpdateRequest = null;
        AccessKey response = api.updateAccessKey(subAccountId, key, accessKeyUpdateRequest);
        // TODO: test validations
    }

}
