/*
 * Cloudinary Account Provisioning API
 * Accounts with provisioning API access can create and manage their **product environments**, **users** and **user groups** using the RESTful Provisioning API.   Provisioning API access is available [upon request](https://cloudinary.com/contact?plan=enterprise) for accounts on an [Enterprise plan](https://cloudinary.com/pricing#pricing-enterprise).  The API uses **Basic Authentication** over HTTPS. Your **Provisioning Key** and **Provisioning Secret** are used for the authentication. These credentials (as well as your ACCOUNT_ID) are located in the [Cloudinary Console](https://console.cloudinary.com/pm) under **Settings > Account > Provisioning API Access**, or they can be obtained from the provisioning environment variable available on your Cloudinary Console [Dashboard](https://console.cloudinary.com/pm/developer-dashboard).  The Provisioning API has dedicated SDKs for the following languages:  * [JavaScript](https://github.com/cloudinary/account-provisioning-js) * [PHP](https://github.com/cloudinary/account-provisioning-php) * [Java](https://github.com/cloudinary/account-provisioning-java)  Useful links: * [Provisioning API reference (Classic)](https://cloudinary.com/documentation/provisioning_api_1) 
 *
 * The version of the OpenAPI document: 0.1.2
 * Contact: support@cloudinary.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudinary.account.provisioning.api;

import com.cloudinary.account.provisioning.ApiException;
import com.cloudinary.account.provisioning.model.CreateUserRequest;
import com.cloudinary.account.provisioning.model.ErrorResponse;
import java.time.LocalDate;
import com.cloudinary.account.provisioning.model.SuccessResponse;
import com.cloudinary.account.provisioning.model.User;
import com.cloudinary.account.provisioning.model.UserRequest;
import com.cloudinary.account.provisioning.model.UsersResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
@Disabled
public class UsersApiTest {

    private final UsersApi api = new UsersApi();

    /**
     * Create user
     *
     * Create a new user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createUserTest() throws ApiException {
        CreateUserRequest createUserRequest = null;
        User response = api.createUser(createUserRequest);
        // TODO: test validations
    }

    /**
     * Delete user
     *
     * Delete a specific user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteUserTest() throws ApiException {
        String userId = null;
        SuccessResponse response = api.deleteUser(userId);
        // TODO: test validations
    }

    /**
     * Get user
     *
     * Retrieve a specific user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUserTest() throws ApiException {
        String userId = null;
        User response = api.getUser(userId);
        // TODO: test validations
    }

    /**
     * Get users
     *
     * Returns an array of all users in the account, or if conditions are specified, returns the relevant users. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUsersTest() throws ApiException {
        Boolean pending = null;
        List<String> ids = null;
        List<String> emails = null;
        String prefix = null;
        String subAccountId = null;
        Boolean lastLogin = null;
        LocalDate from = null;
        LocalDate to = null;
        String unionType = null;
        String sortOrder = null;
        String sortBy = null;
        Integer page = null;
        Integer pageSize = null;
        UsersResponse response = api.getUsers(pending, ids, emails, prefix, subAccountId, lastLogin, from, to, unionType, sortOrder, sortBy, page, pageSize);
        // TODO: test validations
    }

    /**
     * Update user
     *
     * Update the details of a user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateUserTest() throws ApiException {
        String userId = null;
        UserRequest userRequest = null;
        User response = api.updateUser(userId, userRequest);
        // TODO: test validations
    }

}
