/*
 * Cloudinary Provisioning API
 * Accounts with provisioning API access can create and manage their **product environments**, **users** and **user groups** using the RESTful Provisioning API.   Provisioning API access is available [upon request](https://cloudinary.com/contact?plan=enterprise) for accounts on an [Enterprise plan](https://cloudinary.com/pricing#pricing-enterprise). 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@cloudinary.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudinary.provisioning.model;

import java.util.Objects;
import java.util.Arrays;
import com.cloudinary.provisioning.model.AccessKeyResponse;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.cloudinary.provisioning.JSON;

/**
 * AccessKeysResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-14T13:08:19.875333+02:00[Asia/Jerusalem]")
public class AccessKeysResponse {
  public static final String SERIALIZED_NAME_ACCESS_KEYS = "access_keys";
  @SerializedName(SERIALIZED_NAME_ACCESS_KEYS)
  private List<AccessKeyResponse> accessKeys = null;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private Integer total;

  public AccessKeysResponse() { 
  }

  public AccessKeysResponse accessKeys(List<AccessKeyResponse> accessKeys) {
    
    this.accessKeys = accessKeys;
    return this;
  }

  public AccessKeysResponse addAccessKeysItem(AccessKeyResponse accessKeysItem) {
    if (this.accessKeys == null) {
      this.accessKeys = new ArrayList<>();
    }
    this.accessKeys.add(accessKeysItem);
    return this;
  }

   /**
   * Get accessKeys
   * @return accessKeys
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<AccessKeyResponse> getAccessKeys() {
    return accessKeys;
  }


  public void setAccessKeys(List<AccessKeyResponse> accessKeys) {
    this.accessKeys = accessKeys;
  }


  public AccessKeysResponse total(Integer total) {
    
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotal() {
    return total;
  }


  public void setTotal(Integer total) {
    this.total = total;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessKeysResponse accessKeysResponse = (AccessKeysResponse) o;
    return Objects.equals(this.accessKeys, accessKeysResponse.accessKeys) &&
        Objects.equals(this.total, accessKeysResponse.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessKeys, total);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessKeysResponse {\n");
    sb.append("    accessKeys: ").append(toIndentedString(accessKeys)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("access_keys");
    openapiFields.add("total");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AccessKeysResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (AccessKeysResponse.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in AccessKeysResponse is not found in the empty JSON string", AccessKeysResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      //for (Entry<String, JsonElement> entry : entries) {
        //if (!AccessKeysResponse.openapiFields.contains(entry.getKey())) {
          //throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AccessKeysResponse` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        //}
      //}
      JsonArray jsonArrayaccessKeys = jsonObj.getAsJsonArray("access_keys");
      if (jsonArrayaccessKeys != null) {
        // ensure the json data is an array
        if (!jsonObj.get("access_keys").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `access_keys` to be an array in the JSON string but got `%s`", jsonObj.get("access_keys").toString()));
        }

        // validate the optional field `access_keys` (array)
        for (int i = 0; i < jsonArrayaccessKeys.size(); i++) {
          AccessKeyResponse.validateJsonObject(jsonArrayaccessKeys.get(i).getAsJsonObject());
        };
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AccessKeysResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AccessKeysResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AccessKeysResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AccessKeysResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<AccessKeysResponse>() {
           @Override
           public void write(JsonWriter out, AccessKeysResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AccessKeysResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AccessKeysResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AccessKeysResponse
  * @throws IOException if the JSON string is invalid with respect to AccessKeysResponse
  */
  public static AccessKeysResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AccessKeysResponse.class);
  }

 /**
  * Convert an instance of AccessKeysResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

